:: this script is autogenerated by 'gradle startscripts'
:: it starts a las2peer node providing the service 'i5.las2peer.services.gamificationBotWrapperService.GamificationBotWrapperService' of this project
:: pls execute it from the bin folder of your deployment by double-clicking on it
%~d0
cd %~p0
cd ..
set BASE=%CD%
set CLASSPATH="%BASE%/lib/*;"
java -cp %CLASSPATH% i5.las2peer.tools.L2pNodeLauncher --port 9011 --service-directory service uploadStartupDirectory startService('i5.las2peer.services.gamificationBotWrapperService.GamificationBotWrapperService@0.1') startWebConnector interactive
pause
