copy gamification.properties GamificationAchievementService\etc\i5.las2peer.services.gamificationAchievementService.GamificationAchievementService.properties
copy gamification.properties GamificationActionService\etc\i5.las2peer.services.gamificationActionService.GamificationActionService.properties
copy gamification.properties GamificationApplicationService\etc\i5.las2peer.services.gamificationApplicationService.GamificationApplicationService.properties
copy gamification.properties GamificationBadgeService\etc\i5.las2peer.services.gamificationBadgeService.GamificationBadgeService.properties
copy gamification.properties GamificationLevelService\etc\i5.las2peer.services.gamificationLevelService.GamificationLevelService.properties
copy gamification.properties GamificationPointService\etc\i5.las2peer.services.gamificationPointService.GamificationPointService.properties
copy gamification.properties GamificationQuestService\etc\i5.las2peer.services.gamificationQuestService.GamificationQuestService.properties
copy gamification.properties GamificationVisualizationService\etc\i5.las2peer.services.gamificationVisualizationService.GamificationVisualizationService.properties