#!/bin/bash
# this script is autogenerated by 'gradle startscripts'
# it starts a las2peer node providing the service 'i5.las2peer.services.gamificationGameService.GamificationGameService' of this project
# pls execute it from the root folder of your deployment, e. g. ./etc/bin/start_network.sh
java -cp "lib/*" i5.las2peer.tools.L2pNodeLauncher --port 9011 --service-directory service uploadStartupDirectory startService\(\'i5.las2peer.services.gamificationGameService.GamificationGameService@0.1\'\) startWebConnector interactive
