apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: gamification
  name: gamification-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: gamification
  template: 
    metadata: 
      labels: 
        app: gamification
    spec: 
      containers: 
        - 
          image: david3941/gamificationframeworkimage:0.0.6
          name: gamification
          ports: 
            - 
              containerPort: 8080
          env:
            - name: jdbcUrl
              value: "jdbc:postgresql://gamification-db-service.ma-almeida:5432/"
            - name: successAwarenessModelJdbcUrl
              value: "jdbc:mysql://gamification-data-processing-db-service.ma-almeida:3306/"
            - name: successAwarenessHost
              value: "gamification-data-processing-db-service.ma-almeida"
            - name: successAwarenessPort
              value: "3306"
          command: ["/bin/sh","-c"]
          args: ["./main.sh -s; ./main.sh -m build && ./main.sh -r start_one_node"]
