apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: gamification
  name: gamification-db
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: gamification
  template: 
    metadata: 
      labels: 
        app: gamification
    spec: 
      containers: 
        - 
          image: david3941/gamificationframework_database_image:0.0.1
          name: gamification-db
          ports: 
            - 
              containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "postgresql"