# Generated API Documentation

## Important Notes

- Do NOT edit files in subdirectories!
- The API documentation for each service is generated from the `swagger.json` which is derived from the code automatically
- Check the `convertSwagger2markup` and `swagger` tasks in each `build.gradle` for more details.
- Only the `README.adoc` in this directory is handwritten and may be modified by hand.

## Build Instructions

Please run the `generatedSwaggerDocumentation` and `convertSwagger2markup` tasks after modifying the API annotations.
This will update the documentation files, which then can be committed to the repository.

Sometimes, you may have to delete the generated files before they are updated by Gradle.

## Future Work

Someone could improve the build process in the future.
Ideally, the documentation is generated by a GitHub action after every commit and
is deployed to the GitHub Wiki for this project.
